### PR TITLE
[ Awaiting Review ] Implement WENO Scheme 

### LINKED ISSUE #102: inplement finite difference WENO schemes
Hi,

I'm wondering if it is possible to add finite volumes for conservative PDEs in the future?

Thank you for your great work btw

### LINKED ISSUE #136: Move to extrapolation based boundary proximity handling
Currently we use a stencil centrepoint shifting method to deal with domain edges, I propose moving to an extrapolation based approach to ensure stability, adding extra ghostpoints to pad the domain

### LINKED ISSUE #141: 2D incompressible MHD equations
Hi,

I want to see if this package can solve a system of 2D compressible ideal magnetohydrodynamic equations in the X-Z plane.

## Problem Description

The original equations are

$$
\begin{align}
   \frac{\partial\rho}{\partial t} &= -\mathbf{u}\cdot\nabla\rho - \rho\nabla\cdot\mathbf{u}, \\
   \frac{\partial p}{\partial t} &= -\mathbf{u}\cdot\nabla p - \gamma p \nabla\cdot\mathbf{u}, \\
   \frac{\partial \mathbf{u}}{\partial t} &= -\rho\mathbf{u}\cdot\nabla\mathbf{u} -\nabla p - \frac{1}{\mu_0}\nabla\frac{B^2}{2} + \frac{1}{\mu_0}\mathbf{B}\cdot\nabla\mathbf{B} + \nu\nabla^2\mathbf{u}, \\
   \frac{\partial \mathbf{B}}{\partial t} &= \nabla\times\mathbf{u}\times\mathbf{B} - \nabla\times[\eta\nabla\times\mathbf{B}].
\end{align}
$$

Since $\nabla\cdot\mathbf{B}=0$, instead of solving the magnetic field directly, we can solve for the magnetic vector potential $\mathbf{A}$.
Let $$\mathbf{B} = \nabla\times\mathbf{A} = \nabla\times(0, A_y, 0) = (-\frac{\partial A_y}{\partial z}, 0, \frac{\partial A_y}{\partial x})$$, the last equation above can be simplified to

$$
\frac{\partial\mathbf{A}}{\partial t} = \mathbf{u}\times(\nabla\times\mathbf{A}) - \eta\nabla\times(\nabla\times\mathbf{A}).
$$

The normalized 2D equations can be written as

$$
\begin{align}
\frac{\partial\rho}{\partial t} &= -u_x\frac{\partial \rho}{\partial x} - u_z\frac{\partial \rho}{\partial z} - \rho\Big( \frac{\partial u_x}{\partial x} + \frac{\partial u_z}{\partial z} \Big), \\
\frac{\partial p}{\partial t} &= -u_x\frac{\partial p}{\partial x} - u_z\frac{\partial p}{\partial z} - \gamma p\Big( \frac{\partial u_x}{\partial x} + \frac{\partial u_z}{\partial z} \Big), \\
\frac{\partial u_x}{\partial t} &= -u_x\frac{\partial u_x}{\partial x} - u_z\frac{\partial u_x}{\partial z} - \frac{1}{\rho}\frac{\partial}{\partial x}\Big( p + \frac{B^2}{2} \Big) + \frac{1}{\rho}\Big( B_x\frac{\partial Bx}{\partial x} + B_z\frac{\partial Bx}{\partial z} \Big) + \frac{1}{\rho}\nu_m\Big( \frac{\partial^2 u_x}{\partial x^2} + \frac{\partial^2 u_x}{\partial z^2} \Big), \\
\frac{\partial u_z}{\partial t} &= -u_x\frac{\partial u_z}{\partial x} - u_z\frac{\partial u_z}{\partial z} - \frac{1}{\rho}\frac{\partial}{\partial z}\Big( p + \frac{B^2}{2} \Big) + \frac{1}{\rho}\Big( B_x\frac{\partial Bz}{\partial x} + B_z\frac{\partial Bz}{\partial z} \Big) + \frac{1}{\rho}\nu_m\Big( \frac{\partial^2 u_z}{\partial x^2} + \frac{\partial^2 u_z}{\partial z^2} \Big), \\
\frac{\partial A_y}{\partial t} &= u_x\frac{\partial A_y}{\partial x} - u_z\frac{\partial A_y}{\partial z} + \eta_m\Big( \frac{\partial A_y}{\partial x^2} + \frac{\partial A_y}{\partial z^2} \Big)
\end{align}
$$

where $\gamma= 5/3$ is the adiabatic index, $\nu_m, \eta_m$ are some normalized constants, and

$$
\begin{align}
B^2 = B_x^2 + B_z^2.
\end{align}
$$

## Solving with MethodOfLines.jl

Based on my understanding of the examples given in the tutorials, in principle we shall be able to solve this. For simplicity, I set $\eta_m = 0$ and $\nu_m = 0$. Here is my attempt:

<details><summary>Solving with MethodOfLines.jl</summary>
<p>
```julia
# 2D magnetic reconnection for GEM challenge solved using MethodOfLines.jl.
#
# Initial condition:
#   Harris sheet equilibrium with perturbation
#
# Configuration:
#			z
#		 Lz/2   | conducting, Bz = ∂Bz/∂z = ∂By/∂z = 0
#		         |
#                       |                        periodic
#  -Lx/2                |                        Lx/2
#  --------------------------------------------> x
#                    	|
#                    	|
#                    	|
#				      -Lz/2 | conducting, Bz = ∂Bz/∂z = ∂By/∂z = 0
#
# Ref:
#   [Fu1995], section 7.4 and Appendix 2
#   [Birn+2001]( https://doi.org/10.1029/1999JA900449)

using ModelingToolkit, MethodOfLines, OrdinaryDiffEq, DomainSets

const Lx = 25.6
const Lz = 12.8
const nx = 16
const nz = 16
"background field"
const B₀ = 1.0
"mass density"
const ρ₀ = 1.0
"mass density at infinity"
const ρ∞ = 0.2*ρ₀
"width of current sheet"
const λ = 0.5
"perturbation amplitude of the magnetic flux"
const ψ₀ = 0.1
"initial plasma β"
const β = 1.0
"Alfven velocity"
#const va = √(B₀^2/ρ₀)
"pressure normalization parameter"
const p₀ = 0.5*β*B₀^2
"temperature normalization parameter"
#const T₀ = 0.5*β*va^2

# physical parameters in MHD equations
"adiabatic index"
const γ = 5/3
const η = 0.0 # η/(va*L₀)
const ν = 0.0 # μ/(va*L₀*ρ₀)

@parameters x z t
#@parameters η, ν
@variables ρ(..) p(..) ux(..) uz(..) Ay(..) Bx(..) Bz(..)
Dt = Differential(t)
Dx = Differential(x)
Dz = Differential(z)
Dxx = Differential(x)^2
Dzz = Differential(z)^2

∇²(u) = Dxx(u) + Dzz(u)

x_min = -Lx/2
z_min = -Lz/2
t_min = 0.0
x_max = Lx/2
z_max = Lz/2
t_max = 10.0

dx = Lx / nx
dz = Lz / nz

ψ(x,z,t) = ψ₀*cos(2π*x/Lx)*cos(π*z/Lz)

ρ0(x,z,t) = ρ₀*sech(z/λ)^2 + ρ∞

p0(x,z,t) = begin
   b = B₀*tanh(z/λ)
   p₀ + 0.5*(B₀^2 - b^2)
end

ux0(x,z,t) = 0.0
uz0(x,z,t) = 0.0

Bx0(x,z,t) = B₀*tanh(z/λ) + ψ₀*(-π/Lz)*cos(2π*x/Lx)*sin(π*z/Lz)
Bz0(x,z,t) = 0.0 + ψ₀*(-2π/Lx)*sin(2π*x/Lx)*cos(π*z/Lz)

Ay0(x,z,t) = B₀*λ*log(cosh(z)) + ψ(x,z,t)

eq = [
   Dt(ρ(x,z,t)) ~
      -ux(x,z,t)*Dx(ρ(x,z,t)) - uz(x,z,t)*Dz(ρ(x,z,t)) -
      ρ(x,z,t)*(Dx(ux(x,z,t)) + Dz(uz(x,z,t))),
   Dt(p(x,z,t)) ~
      -ux(x,z,t)*Dx(p(x,z,t)) - uz(x,z,t)*Dz(p(x,z,t)) -
      γ*p(x,z,t)*(Dx(ux(x,z,t)) + Dz(uz(x,z,t))),
   Dt(ux(x,z,t)) ~
      -ux(x,z,t)*Dx(ux(x,z,t)) - uz(x,z,t)*Dz(ux(x,z,t)) +
      1/ρ(x,z,t)*(Bx(x,z,t)*Dx(Bx(x,z,t)) + Bz(x,z,t)*Dz(Bx(x,z,t)) - Dx(p(x,z,t)) -
      (Bx(x,z,t)*Dx(Bx(x,z,t)) + Bz(x,z,t)*Dx(Bz(x,z,t))) +
      ν*∇²(ux(x,z,t))),
   Dt(uz(x,z,t)) ~
      -ux(x,z,t)*Dx(uz(x,z,t)) - uz(x,z,t)*Dz(uz(x,z,t)) +
      1/ρ(x,z,t)*(Bx(x,z,t)*Dx(Bz(x,z,t)) + Bz(x,z,t)*Dz(Bz(x,z,t)) - Dz(p(x,z,t)) -
      (Bx(x,z,t)*Dz(Bx(x,z,t)) + Bz(x,z,t)*Dz(Bz(x,z,t))) +
      ν*∇²(uz(x,z,t))),
   Dt(Ay(x,z,t)) ~
      -ux(x,z,t)*Dx(Ay(x,z,t)) - uz(x,z,t)*Dz(Ay(x,z,t)) +
      η*∇²(Ay(x,z,t)),
   Bx(x,z,t) ~ -Dz(Ay(x,z,t)),
   Bz(x,z,t) ~ Dx(Ay(x,z,t))
   ]

domains = [x ∈ Interval(x_min, x_max),
           z ∈ Interval(z_min, z_max),
           t ∈ Interval(t_min, t_max)]

# BCs: periodic in x, Neumann in z
# ICs: set from functions
bcs = [ρ(x,z,0) ~ ρ0(x,z,0),
       ρ(x_min,z,t) ~ ρ(x_max,z,t),
       Dz(ρ(x,z_min,t)) ~ 0.0,
       Dz(ρ(x,z_max,t)) ~ 0.0,

       p(x,z,0) ~ p0(x,z,0),
       p(x_min,z,t) ~ p(x_max,z,t),
       Dz(p(x,z_min,t)) ~ 0.0,
       Dz(p(x,z_max,t)) ~ 0.0,
       
       ux(x,z,0) ~ ux0(x,z,0),
       ux(x_min,z,t) ~ ux(x_max,z,t),
       Dz(ux(x,z_min,t)) ~ 0.0,
       Dz(ux(x,z_max,t)) ~ 0.0,
       
       uz(x,z,0) ~ uz0(x,z,0),
       uz(x_min,z,t) ~ uz(x_max,z,t),
       Dz(uz(x,z_min,t)) ~ 0.0,
       Dz(uz(x,z_max,t)) ~ 0.0,
       
       Ay(x,z,0) ~ Ay0(x,z,0),
       Ay(x_min,z,t) ~ Ay(x_max,z,t),
       Dz(Ay(x,z_min,t)) ~ 0.0,
       Dz(Ay(x,z_max,t)) ~ 0.0,

       Bx(x,z,0) ~ Bx0(x,z,0),
       Bx(x_min,z,t) ~ Bx(x_max,z,t),
       Dz(Bx(x,z_min,t)) ~ 0.0,
       Dz(Bx(x,z_max,t)) ~ 0.0,
       
       Bz(x,z,0) ~ Bz0(x,z,0),
       Bz(x_min,z,t) ~ Bz(x_max,z,t),
       Dz(Bz(x,z_min,t)) ~ 0.0,
       Dz(Bz(x,z_max,t)) ~ 0.0,
      ]

@named pdesys = PDESystem(eq, bcs, domains,
   [x,z,t],
   [ρ(x,z,t), p(x,z,t), ux(x,z,t), uz(x,z,t), Ay(x,z,t), Bx(x,z,t), Bz(x,z,t)])

## Discretization

order = 2

discretization = MOLFiniteDifference([x=>dx, z=>dz], t, approx_order=order, grid_align=center_align)

## Convert the PDE problem into an ODE problem
println("Discretization:")
@time prob = discretize(pdesys, discretization)

println("Solve:")
#@time sol = solve(prob, Tsit5(), saveat=0.1)
@time sol = solve(prob, RK4(), dt=0.05, saveat=0.1)

## Extracting results
grid = get_discrete(pdesys, discretization)
discrete_x = grid[x]
discrete_z = grid[z]
discrete_t = sol[t]

@time solBx = map(d -> sol[d][end], grid[Bx(x, z, t)])
solBz = map(d -> sol[d][end], grid[Bz(x, z, t)])
solρ = map(d -> sol[d][end], grid[ρ(x, z, t)])
```
</p>
</details>

For plotting, I use PyPlot

<details><summary>Plotting script</summary>
<p>
```julia
using PyPlot

@static if matplotlib.__version__ < "3.5"
   matplotlib.rc("pcolor", shading="nearest") # newer version default "auto"
end

matplotlib.rc("font", size=14)
matplotlib.rc("xtick", labelsize=10)
matplotlib.rc("ytick", labelsize=10)

function plot_snapshot(xrange, zrange, bx, bz)
	# meshgrid: note the array ordering difference between Julia and Python!
	X = [i for _ in zrange, i in xrange]
	Z = [j for j in zrange, _ in xrange]

	fig, ax = subplots(1,1, figsize=(12,8), constrained_layout=true)

	im = ax.pcolormesh(xrange, zrange, bz', cmap=matplotlib.cm.RdBu_r)
	ax.streamplot(X, Z, bx', bz', color="k")

	ax.set_xlabel("x")
	ax.set_ylabel("z")

	ax.set_title("Bz")

	fig.colorbar(im; ax)

	return
end

figure()
pcolormesh(discrete_x, discrete_z, solρ', cmap=matplotlib.cm.RdBu_r, shading="nearest")
xlabel("x")
ylabel("z")
colorbar()

plot_snapshot(discrete_x, discrete_z, solBx, solBz)
```
</p>
</details>

## Testing

I hope I don't make mistakes in expressing the system of PDEs, but the test result is not quite what I expect: it quickly develops some numerical instabilities. As a comparison, here is my hand-written script for solving the PDEs with RK4 in time (fixed timestep) and central differencing in space:

<details><summary>Hand-written finite difference code</summary>
<p>

```julia
using PyPlot

@static if matplotlib.__version__ ≥ "3.3"
   matplotlib.rc("image", cmap="turbo") # set default colormap
end

@static if matplotlib.__version__ < "3.5"
   matplotlib.rc("pcolor", shading="nearest") # newer version default "auto"
end

matplotlib.rc("font", size=14)
matplotlib.rc("xtick", labelsize=10)
matplotlib.rc("ytick", labelsize=10)

Base.@kwdef struct Parameter
   Lx::Float64 = 25.6
   Lz::Float64 = 12.8
   nx::Int = 18 #34
   nz::Int = 18 #34
   nt::Int = 600
   "background field"
   B₀::Float64 = 1.0
   "mass density"
   ρ₀::Float64 = 1.0
   "mass density at infinity"
   ρ∞::Float64 = 0.2*ρ₀
   "width of current sheet"
   λ::Float64 = 0.5
   "perturbation amplitude of the magnetic flux"
   ψ₀::Float64 = 0.1
   "initial plasma β"
	β::Float64 = 1.0
   "Alfven velocity"
	va::Float64 = √(B₀^2/ρ₀)
   "pressure normalization parameter"
	p₀::Float64 = 0.5*β*B₀^2
   "temperature normalization parameter"
	T₀::Float64 = 0.5*β*va^2

	# physical parameters in MHD equations
   "adiabatic index"
	γ::Float64 = 5/3
	η::Float64 = 0.0 # η/(va*L₀)
	ν::Float64 = 0.0 # μ/(va*L₀*ρ₀)

   "output cadence"
	nplot::Int = 600

   # array indices for different variables
	ρ_::Int = 1
	p_::Int = 2
	ux_::Int = 3
	uz_::Int = 4
	ay_::Int = 5

   dx::Float64 = Lx/nx
   dz::Float64 = Lz/nz
   dt::Float64 = 0.05     # giving a dt < min(dx,dz)/(√(1.0+0.5*γ*β)*va)
   inv2dx::Float64 = nx/(2*Lx)
   inv2dz::Float64 = nz/(2*Lz)
   invdx²::Float64 = (nx/Lx)^2
   invdz²::Float64 = (nz/Lz)^2
end

struct Variable
	state::Array{Float64,3}
	statetmp::Array{Float64,3}

   bx::Array{Float64,2}
   bz::Array{Float64,2}
   "total pressure"
   pt::Array{Float64,2}
   "maximum bz magnitudes"
   bzm::Vector{Float64}
	# intermediate arrays for rk4
   rrho::Array{Float64,2} # 1/rho
   f1::Array{Float64,3}
   f2::Array{Float64,3}
   f3::Array{Float64,3}
   f4::Array{Float64,3}

   function Variable(nx::Int, nz::Int, nt::Int)
      state = zeros(nx, nz, 5)
      statetmp = zeros(nx, nz, 5)
      bx = zeros(nx, nz)
      bz = zeros(nx, nz)
      pt = zeros(nx, nz) # pt = p + b^2/2
      bzm = zeros(nt)
      rrho = zeros(nx, nz)
      f1 = zeros(nx, nz, 5)
      f2 = zeros(nx, nz, 5)
      f3 = zeros(nx, nz, 5)
      f4 = zeros(nx, nz, 5)
      new(state, statetmp, bx, bz, pt, bzm, rrho, f1, f2, f3, f4)
   end
end


function solve!(param::Parameter, var::Variable)
   (;nt, dt, nplot, ρ_, p_) = param
   (;state, bzm) = var

   t = 0.0

	set_initial_condition!(param, var)

	fig, cs = save_snapshot(param, var)

	for it = 1:nt
		bzm[it] = get_bzmax(param, var)
		if mod(it-1, nplot) == 0
			println(it, ", max(Bz) = ", bzm[it])
         save_snapshot!(var, it, fig, cs)
			#sleep(2.0)
		end

		t += dt
		update!(param, var)

		ρmin = @views minimum(state[2:end-1,2:end-1,ρ_])
		pmin = @views minimum(state[2:end-1,2:end-1,p_])

		if ρmin < 0
			index = @views argmin(state[:,:,ρ_])
			@info index, state[index[1],index[2],ρ_]
			error("Negative density at step $it")
		end

		if pmin < 0
			index = @views argmin(state[:,:,p_])
			@info index, state[index[1],index[2],p_]
			error("Negative pressure at step $it")
		end
	end

	println("Finished at step $nt, t = $t")

   return
end

"""
	set_initial_condition(param::Parameter, var::Variable)

Set initial condition as a perturbation to the Harris current sheet equilibrium.
"""
function set_initial_condition!(param::Parameter, var::Variable)
   (;nx, nz, Lx, Lz, B₀, ρ₀, ρ∞, p₀, λ, ψ₀, ρ_, p_, ay_) = param
   (; state) = var

   x = range(-Lx/2, Lx/2, length=nx)
   z = range(-Lz/2, Lz/2, length=nz)

	state .= 0.0
   # Harris current sheet
   for k in eachindex(z)
      ρ = ρ₀*sech(z[k]/λ)^2 + ρ∞ # (p₀ + 0.5*(B₀^2 - b^2)) / T₀
      b = B₀*tanh(z[k]/λ)
      state[2:end-1,k,ay_] .= B₀*λ*log(cosh(z[k]))
      state[2:end-1,k,ρ_] .= ρ
      state[2:end-1,k,p_] .= p₀ + 0.5*(B₀^2 - b^2)
   end

   # Perturbation in B, or flux function
   for k in eachindex(z), i in eachindex(x)
      #δBx = ψ₀*(-π/Lz)*cos(2πx[i]/Lx)*sin(πz[k]/Lz)
      #δBz = ψ₀*(-2π/Lx)*sin(2πx[i]/Lx)*cos(πz[k]/Lz)
      state[i,k,ay_] += ψ₀*cos(2π*x[i]/Lx)*cos(π*z[k]/Lz)
   end

   # Neumann B.C. in z
   state[:,1,:] = state[:,2,:]
   state[:,end,:] = state[:,end-1,:]

   # periodic B.C. in x
   state[1,:,:] = state[end-1,:,:]
   state[end,:,:] = state[2,:,:]

   return
end

"""
    update!(param::Parameter, var::Variable)

One step update with 1st order in time and RK4 in space.
"""
function update!(param::Parameter, var::Variable)
   (;dt) = param
   (;state, statetmp, f1, f2, f3, f4) = var

	rhs!(param, var, f1, state)
	@. statetmp = state + 0.5*dt*f1
	rhs!(param, var, f2, statetmp)
	@. statetmp = state + 0.5*dt*f2
	rhs!(param, var, f3, statetmp)
	@. statetmp = state + dt*f3
	rhs!(param, var, f4, statetmp)
	@. state += dt*(f1 + 2.0*f2 + 2.0*f3 + f4)/6.0

	return
end

"Compute for rk4 the right hand side of mhd equations."
function rhs!(param::Parameter, var::Variable, varout::Array{Float64,3}, varin::Array{Float64,3})
   (;nx, nz, inv2dx, inv2dz, invdx², invdz², γ, ν, η, ρ_, p_, ux_, uz_, ay_) = param
   (;rrho, bx, bz, pt) = var

	# calculate Bx, Bz
	calcb!(param, var, varin)

	for i = 2:nx-1, j = 2:nz-1
		rrho[i,j] = 1.0 / varin[i,j,ρ_]
		pt[i,j] = varin[i,j,p_] + 0.5*(bx[i,j]^2 + bz[i,j]^2)
	end

	set_BC!(param, rrho)
	set_BC!(param, pt)

	for j = 2:nz-1
		jm = j - 1
		jp = j + 1
		for i = 2:nx-1
			varout[i,j,ρ_] =
            -varin[i,j,ux_]*inv2dx*(varin[i+1,j , ρ_] - varin[i-1,j , ρ_]) -
             varin[i,j,uz_]*inv2dz*(varin[i  ,jp, ρ_] - varin[i  ,jm, ρ_]) -
             varin[i,j,ρ_]*(inv2dx*(varin[i+1,j ,ux_] - varin[i-1,j ,ux_]) +
				                inv2dz*(varin[i  ,jp,uz_] - varin[i  ,jm,uz_]))

			varout[i,j,p_] =
            -varin[i,j,ux_]*inv2dx*(varin[i+1,j ,p_] - varin[i-1,j ,p_]) -
				 varin[i,j,uz_]*inv2dz*(varin[i  ,jp,p_] - varin[i  ,jm,p_]) -
				γ*varin[i,j,p_]*(inv2dx*(varin[i+1,j ,ux_] - varin[i-1,j ,ux_]) +
								     inv2dz*(varin[i  ,jp,uz_] - varin[i  ,jm,uz_]))

			varout[i,j,ux_] =
            -varin[i,j,ux_]*inv2dx*(varin[i+1,j ,ux_] - varin[i-1,j ,ux_]) -
             varin[i,j,uz_]*inv2dz*(varin[i  ,jp,ux_] - varin[i  ,jm,ux_]) +
            rrho[i,j]*( (bx[i,j]*inv2dx*(bx[i+1,j ] - bx[i-1,j ]) +
            				 bz[i,j]*inv2dz*(bx[i  ,jp] - bx[i  ,jm]) -
								         inv2dx*(pt[i+1,j ] - pt[i-1,j ])) +
            ν*(invdx²*(varin[i+1,j ,ux_] + varin[i-1,j ,ux_] - 2.0*varin[i,j,ux_]) +
               invdz²*(varin[i  ,jp,ux_] + varin[i  ,jm,ux_] - 2.0*varin[i,j,ux_])) )

			varout[i,j,uz_] =
            -varin[i,j,ux_]*inv2dx*(varin[i+1,j ,uz_] - varin[i-1,j ,uz_]) -
             varin[i,j,uz_]*inv2dz*(varin[i  ,jp,uz_] - varin[i  ,jm,uz_]) +
            rrho[i,j]*( (bx[i,j]*inv2dx*(bz[i+1,j ] - bz[i-1,j ]) +
            				 bz[i,j]*inv2dz*(bz[i  ,jp] - bz[i  ,jm]) -
            							inv2dz*(pt[i  ,jp] - pt[i  ,jm])) +
            ν*(invdx²*(varin[i+1,j ,uz_] + varin[i-1,j ,uz_] - 2.0*varin[i,j,uz_]) +
            	invdz²*(varin[i  ,jp,uz_] + varin[i  ,jm,uz_] - 2.0*varin[i,j,uz_])) )

			varout[i,j,ay_] =
            -varin[i,j,ux_]*inv2dx*(varin[i+1,j ,ay_] - varin[i-1,j ,ay_]) -
             varin[i,j,uz_]*inv2dz*(varin[i  ,jp,ay_] - varin[i  ,jm,ay_]) +
            η*(invdx²*(varin[i+1,j ,ay_] + varin[i-1,j ,ay_] - 2.0*varin[i,j,ay_]) +
            	invdz²*(varin[i  ,jp,ay_] + varin[i  ,jm,ay_] - 2.0*varin[i,j,ay_]))
		end
	end

	set_BC!(param, varout)

	return
end

"Calculate Bx, Bz."
function calcb!(param::Parameter, var::Variable, varin::Array{Float64,3})
   (;nx, nz, inv2dx, inv2dz, ay_) = param
   (;bx, bz) = var

	# calculate Bx, Bz
	for i = 2:nx-1, j = 2:nz-1
		jp = j + 1
		jm = j - 1
		bx[i,j] = -inv2dz*(varin[i,jp,ay_] - varin[i,jm,ay_])
		bz[i,j] =  inv2dx*(varin[i+1,j,ay_] - varin[i-1,j,ay_])
	end

	set_BC!(param, bx)
	set_BC!(param, bz)

   return
end

function set_BC!(param::Parameter, var::Array{Float64,2})
	(;nx, nz) = param
	# x
	var[1,2:nz-1]   = var[end-1,2:nz-1]
	var[end,2:nz-1] = var[2,2:nz-1]
	# z
	var[2:nx-1,1]   = var[2:nx-1,2]
	var[2:nx-1,end] = var[2:nx-1,end-1]
end

function set_BC!(param::Parameter, var::Array{Float64,3})
	(;nx, nz, ρ_, p_, ux_, uz_, ay_) = param

	var[1,2:nz-1,ρ_]  = var[end-1,2:nz-1,ρ_]
	var[1,2:nz-1,p_]  = var[end-1,2:nz-1,p_]
	var[1,2:nz-1,ux_] = var[end-1,2:nz-1,ux_]
	var[1,2:nz-1,uz_] = var[end-1,2:nz-1,uz_]
	var[1,2:nz-1,ay_] = var[end-1,2:nz-1,ay_]

	var[end,2:nz-1,ρ_]  = var[2,2:nz-1,ρ_]
	var[end,2:nz-1,p_]  = var[2,2:nz-1,p_]
	var[end,2:nz-1,ux_] = var[2,2:nz-1,ux_]
	var[end,2:nz-1,uz_] = var[2,2:nz-1,uz_]
	var[end,2:nz-1,ay_] = var[2,2:nz-1,ay_]

	# z boundary
	var[2:nx-1,1,ρ_]  = var[2:nx-1,2,ρ_]
	var[2:nx-1,1,p_]  = var[2:nx-1,2,p_]
	var[2:nx-1,1,ux_] = var[2:nx-1,2,ux_]
	var[2:nx-1,1,uz_] = var[2:nx-1,2,uz_]
	var[2:nx-1,1,ay_] = var[2:nx-1,2,ay_]

	var[2:nx-1,end,ρ_]  = var[2:nx-1,end-1,ρ_]
	var[2:nx-1,end,p_]  = var[2:nx-1,end-1,p_]
	var[2:nx-1,end,ux_] = var[2:nx-1,end-1,ux_]
	var[2:nx-1,end,uz_] = var[2:nx-1,end-1,uz_]
	var[2:nx-1,end,ay_] = var[2:nx-1,end-1,ay_]
end

"Calculate Bz max magnitude."
function get_bzmax(param::Parameter, var::Variable)
   # Calculate B
	calcb!(param, var, var.state)

	bzm = maximum(abs, var.bz; init=-100.0)
end


"Save snapshots."
function save_snapshot(param::Parameter, var::Variable)
   (;nx, nz, nt, dx, dz, dt) = param

   xl = dx*(nx-1)/2
   zl = dz*(nz-1)
   xrange = -xl:dx:xl
   zrange = 0:dz:zl
	t = range(0, dt*(nt-1), step=dt)

	# meshgrid: note the array ordering difference between Julia and Python!
	X = [i for _ in zrange, i in xrange]
	Z = [j for j in zrange, _ in xrange]

   fig, axs = subplots(2,2, figsize=(12,8), constrained_layout=true)

	ρmin, ρmax = 0.0, 1.0
	umin, umax = -0.35, 0.35
	bmin, bmax = -0.07, 0.07

	c1 = @views axs[1,1].pcolormesh(xrange, zrange, var.state[:,:,1]'; vmin=ρmin, vmax=ρmax)
	c2 = @views axs[1,2].pcolormesh(xrange, zrange, var.state[:,:,3]'; vmin=umin, vmax=umax,
		cmap=matplotlib.cm.RdBu_r)
	c3 = axs[2,1].pcolormesh(xrange, zrange, var.bz'; vmin=bmin, vmax=bmax,
		cmap=matplotlib.cm.RdBu_r)
	l1 = axs[2,2].plot(t, zero(var.bzm))

	axs[2,2].set_xlim(0, dt*nt)
	axs[2,2].set_ylim(-3.8, -3.2)

	for ax in axs[1:3]
		ax.set_xlabel("x")
		ax.set_ylabel("z")
	end

	im_ratio = length(zrange)/length(xrange)
	fraction = 0.046 * im_ratio

	ticks = (range(ρmin, ρmax, length=7), range(umin, umax, length=7),
		range(bmin, bmax, length=7))

	cb1 = colorbar(c1; ax=axs[1,1], ticks=ticks[1], fraction, pad=0.02)
	cb2 = colorbar(c2; ax=axs[1,2], ticks=ticks[2], fraction, pad=0.02)
	cb3 = colorbar(c3; ax=axs[2,1], ticks=ticks[3], fraction, pad=0.02)

	titles = (L"\rho", "Bz", "Ux", "log(max(Bz))")
	for (ax, title) in zip(axs, titles)
		ax.set_title(title)
	end

   return fig, (c1, c2, c3, l1)
end

"Save snapshots by overwriting `fig` and `axs`."
function save_snapshot!(var::Variable, it::Int, fig, cs)
	fig.suptitle("2D MHD tearing mode, it = $it")
	cs[1].set_array(var.state[:,:,1]')
	cs[2].set_array(var.state[:,:,3]')
	cs[3].set_array(var.bz')
	cs[4][1].set_ydata(log.(var.bzm))

	savefig("$(lpad(it, 4, '0')).png")

	return
end

function plot_snapshot(param::Parameter, var::Variable)
   (;nx, nz, nt, dx, dz, dt) = param
   (;state, bx, bz, bzm) = var

	xl = dx*(nx-1)/2
	zl = dz*(nz-1)
	xrange = -xl:dx:xl
	zrange = 0:dz:zl
	t = range(0, dt*(nt-1), step=dt)

	# meshgrid: note the array ordering difference between Julia and Python!
	X = [i for _ in zrange, i in xrange]
	Z = [j for j in zrange, _ in xrange]

	fig, axs = subplots(2,2, figsize=(12,8), constrained_layout=true)

	im1 = @views axs[1,1].pcolormesh(xrange, zrange, state[:,:,1]')
	im2 = @views axs[1,2].pcolormesh(xrange, zrange, state[:,:,3]', cmap=matplotlib.cm.RdBu_r)
	im3 = axs[2,1].pcolormesh(xrange, zrange, bz', cmap=matplotlib.cm.RdBu_r)
	axs[2,1].streamplot(X, Z, bx', bz', color="k")
	axs[2,2].plot(t, log.(bzm))

	for ax in axs[1:3]
		ax.set_xlabel("x")
		ax.set_ylabel("z")
	end

	titles = (L"\rho", "Bz", "Ux", "log(max(Bz))")
	for (ax, title) in zip(axs, titles)
		ax.set_title(title)
	end

	fig.colorbar(im1, ax=axs[1,1])
	fig.colorbar(im2, ax=axs[1,2])
	fig.colorbar(im3, ax=axs[2,1])

	return
end

##### Main

param = Parameter()

var = Variable(param.nx, param.nz, param.nt)

set_initial_condition!(param, var)
calcb!(param, var, var.state)
plot_snapshot(param, var)

solve!(param, var)

plot_snapshot(param, var)
```

</p>
</details>

With my hand-written script, the initial condition looks like
tearing_init
and the solutions at `t=30` are

tearing_t30_16x16

With the first script using this package, I get rapidly increasing densities, e.g. at `t=1.8` which is a hint for instability

tearing_t1 8_16x16_MethodOfLines_density_wrong

## Troubleshooting

Currently I am uncertain where the problem is. Could you please take a look and offer me some guidance? Thanks!

### LINKED ISSUE #143: Discretization failed
Hey,
I have this lengthy example that fails and tells me

> Discretization failed, please post an issue on https://github.com/SciML/MethodOfLines.jl with the failing code and system at low point count.

So here I am ;)

```
WARNING: both Symbolics and ModelingToolkit export "supremum"; uses of it in module MethodOfLines must be qualified
WARNING: both Symbolics and ModelingToolkit export "infimum"; uses of it in module MethodOfLines must be qualified
The system of equations is:
Equation[(IfElse.ifelse((2Differential(0.075)(α₂[3](t))*Differential(0.075)(Differential(0.075)(α₁[3](t)))) > 0, 2(20.0α₁[3](t) - 20.0α₁[2](t))*Differential(0.075)(α₂[3](t))*Differential(0.075)(Differential(0.075)(α₁[3](t))), 2(20.0α₁[4](t) - 20.0α₁[3](t))*Differential(0.075)(α₂[3](t))*Differential(0.075)(Differential(0.075)(α₁[3](t)))) - 2.0(399.99999999999994α₂[2](t) + 399.99999999999994α₂[4](t) - 799.9999999999999α₂[3](t))*((20.0α₁[3](t) - 20.0α₁[2](t))^2)) / (((20.0α₁[3](t) - 20.0α₁[2](t))^2 + (20.0α₂[3](t) - 20.0α₂[2](t))^2)*α₂[3](t)) + Differential(t)((20.0α₁[3](t) - 20.0α₁[2](t))^2 + (20.0α₂[3](t) - 20.0α₂[2](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.125)(α₂[4](t))*Differential(0.125)(Differential(0.125)(α₁[4](t)))) > 0, 2(20.0α₁[4](t) - 20.0α₁[3](t))*Differential(0.125)(α₂[4](t))*Differential(0.125)(Differential(0.125)(α₁[4](t))), 2(20.0α₁[5](t) - 20.0α₁[4](t))*Differential(0.125)(α₂[4](t))*Differential(0.125)(Differential(0.125)(α₁[4](t)))) - 2.0(399.99999999999994α₂[3](t) + 399.99999999999994α₂[5](t) - 799.9999999999999α₂[4](t))*((20.0α₁[4](t) - 20.0α₁[3](t))^2)) / (((20.0α₁[4](t) - 20.0α₁[3](t))^2 + (20.0α₂[4](t) - 20.0α₂[3](t))^2)*α₂[4](t)) + Differential(t)((20.0α₁[4](t) - 20.0α₁[3](t))^2 + (20.0α₂[4](t) - 20.0α₂[3](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.175)(α₂[5](t))*Differential(0.175)(Differential(0.175)(α₁[5](t)))) > 0, 2(20.0α₁[5](t) - 20.0α₁[4](t))*Differential(0.175)(α₂[5](t))*Differential(0.175)(Differential(0.175)(α₁[5](t))), 2(20.0α₁[6](t) - 20.0α₁[5](t))*Differential(0.175)(α₂[5](t))*Differential(0.175)(Differential(0.175)(α₁[5](t)))) - 2.0(399.99999999999994α₂[4](t) + 399.99999999999994α₂[6](t) - 799.9999999999999α₂[5](t))*((20.0α₁[5](t) - 20.0α₁[4](t))^2)) / (((20.0α₁[5](t) - 20.0α₁[4](t))^2 + (20.0α₂[5](t) - 20.0α₂[4](t))^2)*α₂[5](t)) + Differential(t)((20.0α₁[5](t) - 20.0α₁[4](t))^2 + (20.0α₂[5](t) - 20.0α₂[4](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.225)(α₂[6](t))*Differential(0.225)(Differential(0.225)(α₁[6](t)))) > 0, 2(20.0α₁[6](t) - 20.0α₁[5](t))*Differential(0.225)(α₂[6](t))*Differential(0.225)(Differential(0.225)(α₁[6](t))), 2(20.0α₁[7](t) - 20.0α₁[6](t))*Differential(0.225)(α₂[6](t))*Differential(0.225)(Differential(0.225)(α₁[6](t)))) - 2.0(399.99999999999994α₂[5](t) + 399.99999999999994α₂[7](t) - 799.9999999999999α₂[6](t))*((20.0α₁[6](t) - 20.0α₁[5](t))^2)) / (((20.0α₁[6](t) - 20.0α₁[5](t))^2 + (20.0α₂[6](t) - 20.0α₂[5](t))^2)*α₂[6](t)) + Differential(t)((20.0α₁[6](t) - 20.0α₁[5](t))^2 + (20.0α₂[6](t) - 20.0α₂[5](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.275)(α₂[7](t))*Differential(0.275)(Differential(0.275)(α₁[7](t)))) > 0, 2(20.0α₁[7](t) - 20.0α₁[6](t))*Differential(0.275)(α₂[7](t))*Differential(0.275)(Differential(0.275)(α₁[7](t))), 2(20.0α₁[8](t) - 20.0α₁[7](t))*Differential(0.275)(α₂[7](t))*Differential(0.275)(Differential(0.275)(α₁[7](t)))) - 2.0(399.99999999999994α₂[6](t) + 399.99999999999994α₂[8](t) - 799.9999999999999α₂[7](t))*((20.0α₁[7](t) - 20.0α₁[6](t))^2)) / (((20.0α₁[7](t) - 20.0α₁[6](t))^2 + (20.0α₂[7](t) - 20.0α₂[6](t))^2)*α₂[7](t)) + Differential(t)((20.0α₁[7](t) - 20.0α₁[6](t))^2 + (20.0α₂[7](t) - 20.0α₂[6](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.325)(α₂[8](t))*Differential(0.325)(Differential(0.325)(α₁[8](t)))) > 0, 2(20.0α₁[8](t) - 20.0α₁[7](t))*Differential(0.325)(α₂[8](t))*Differential(0.325)(Differential(0.325)(α₁[8](t))), 2(20.0α₁[9](t) - 20.0α₁[8](t))*Differential(0.325)(α₂[8](t))*Differential(0.325)(Differential(0.325)(α₁[8](t)))) - 2.0(399.99999999999994α₂[7](t) + 399.99999999999994α₂[9](t) - 799.9999999999999α₂[8](t))*((20.0α₁[8](t) - 20.0α₁[7](t))^2)) / (((20.0α₁[8](t) - 20.0α₁[7](t))^2 + (20.0α₂[8](t) - 20.0α₂[7](t))^2)*α₂[8](t)) + Differential(t)((20.0α₁[8](t) - 20.0α₁[7](t))^2 + (20.0α₂[8](t) - 20.0α₂[7](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.375)(α₂[9](t))*Differential(0.375)(Differential(0.375)(α₁[9](t)))) > 0, 2(20.0α₁[9](t) - 20.0α₁[8](t))*Differential(0.375)(α₂[9](t))*Differential(0.375)(Differential(0.375)(α₁[9](t))), 2(20.0α₁[10](t) - 20.0α₁[9](t))*Differential(0.375)(α₂[9](t))*Differential(0.375)(Differential(0.375)(α₁[9](t)))) - 2.0(399.99999999999994α₂[8](t) + 399.99999999999994α₂[10](t) - 799.9999999999999α₂[9](t))*((20.0α₁[9](t) - 20.0α₁[8](t))^2)) / (((20.0α₁[9](t) - 20.0α₁[8](t))^2 + (20.0α₂[9](t) - 20.0α₂[8](t))^2)*α₂[9](t)) + Differential(t)((20.0α₁[9](t) - 20.0α₁[8](t))^2 + (20.0α₂[9](t) - 20.0α₂[8](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.425)(α₂[10](t))*Differential(0.425)(Differential(0.425)(α₁[10](t)))) > 0, 2(20.0α₁[10](t) - 20.0α₁[9](t))*Differential(0.425)(α₂[10](t))*Differential(0.425)(Differential(0.425)(α₁[10](t))), 2(20.0α₁[11](t) - 20.0α₁[10](t))*Differential(0.425)(α₂[10](t))*Differential(0.425)(Differential(0.425)(α₁[10](t)))) - 2.0(399.99999999999994α₂[9](t) + 399.99999999999994α₂[11](t) - 799.9999999999999α₂[10](t))*((20.0α₁[10](t) - 20.0α₁[9](t))^2)) / (((20.0α₁[10](t) - 20.0α₁[9](t))^2 + (20.0α₂[10](t) - 20.0α₂[9](t))^2)*α₂[10](t)) + Differential(t)((20.0α₁[10](t) - 20.0α₁[9](t))^2 + (20.0α₂[10](t) - 20.0α₂[9](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.475)(α₂[11](t))*Differential(0.475)(Differential(0.475)(α₁[11](t)))) > 0, 2(20.0α₁[11](t) - 20.0α₁[10](t))*Differential(0.475)(α₂[11](t))*Differential(0.475)(Differential(0.475)(α₁[11](t))), 2(20.0α₁[12](t) - 20.0α₁[11](t))*Differential(0.475)(α₂[11](t))*Differential(0.475)(Differential(0.475)(α₁[11](t)))) - 2.0(399.99999999999994α₂[10](t) + 399.99999999999994α₂[12](t) - 799.9999999999999α₂[11](t))*((20.0α₁[11](t) - 20.0α₁[10](t))^2)) / (((20.0α₁[11](t) - 20.0α₁[10](t))^2 + (20.0α₂[11](t) - 20.0α₂[10](t))^2)*α₂[11](t)) + Differential(t)((20.0α₁[11](t) - 20.0α₁[10](t))^2 + (20.0α₂[11](t) - 20.0α₂[10](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.525)(α₂[12](t))*Differential(0.525)(Differential(0.525)(α₁[12](t)))) > 0, 2(20.0α₁[12](t) - 20.0α₁[11](t))*Differential(0.525)(α₂[12](t))*Differential(0.525)(Differential(0.525)(α₁[12](t))), 2(20.0α₁[13](t) - 20.0α₁[12](t))*Differential(0.525)(α₂[12](t))*Differential(0.525)(Differential(0.525)(α₁[12](t)))) - 2.0(399.99999999999994α₂[11](t) + 399.99999999999994α₂[13](t) - 799.9999999999999α₂[12](t))*((20.0α₁[12](t) - 20.0α₁[11](t))^2)) / (((20.0α₁[12](t) - 20.0α₁[11](t))^2 + (20.0α₂[12](t) - 20.0α₂[11](t))^2)*α₂[12](t)) + Differential(t)((20.0α₁[12](t) - 20.0α₁[11](t))^2 + (20.0α₂[12](t) - 20.0α₂[11](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.575)(α₂[13](t))*Differential(0.575)(Differential(0.575)(α₁[13](t)))) > 0, 2(20.0α₁[13](t) - 20.0α₁[12](t))*Differential(0.575)(α₂[13](t))*Differential(0.575)(Differential(0.575)(α₁[13](t))), 2(20.0α₁[14](t) - 20.0α₁[13](t))*Differential(0.575)(α₂[13](t))*Differential(0.575)(Differential(0.575)(α₁[13](t)))) - 2.0(399.99999999999994α₂[12](t) + 399.99999999999994α₂[14](t) - 799.9999999999999α₂[13](t))*((20.0α₁[13](t) - 20.0α₁[12](t))^2)) / (((20.0α₁[13](t) - 20.0α₁[12](t))^2 + (20.0α₂[13](t) - 20.0α₂[12](t))^2)*α₂[13](t)) + Differential(t)((20.0α₁[13](t) - 20.0α₁[12](t))^2 + (20.0α₂[13](t) - 20.0α₂[12](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.625)(α₂[14](t))*Differential(0.625)(Differential(0.625)(α₁[14](t)))) > 0, 2(20.0α₁[14](t) - 20.0α₁[13](t))*Differential(0.625)(α₂[14](t))*Differential(0.625)(Differential(0.625)(α₁[14](t))), 2(20.0α₁[15](t) - 20.0α₁[14](t))*Differential(0.625)(α₂[14](t))*Differential(0.625)(Differential(0.625)(α₁[14](t)))) - 2.0(399.99999999999994α₂[13](t) + 399.99999999999994α₂[15](t) - 799.9999999999999α₂[14](t))*((20.0α₁[14](t) - 20.0α₁[13](t))^2)) / (((20.0α₁[14](t) - 20.0α₁[13](t))^2 + (20.0α₂[14](t) - 20.0α₂[13](t))^2)*α₂[14](t)) + Differential(t)((20.0α₁[14](t) - 20.0α₁[13](t))^2 + (20.0α₂[14](t) - 20.0α₂[13](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.675)(α₂[15](t))*Differential(0.675)(Differential(0.675)(α₁[15](t)))) > 0, 2(20.0α₁[15](t) - 20.0α₁[14](t))*Differential(0.675)(α₂[15](t))*Differential(0.675)(Differential(0.675)(α₁[15](t))), 2(20.0α₁[16](t) - 20.0α₁[15](t))*Differential(0.675)(α₂[15](t))*Differential(0.675)(Differential(0.675)(α₁[15](t)))) - 2.0(399.99999999999994α₂[14](t) + 399.99999999999994α₂[16](t) - 799.9999999999999α₂[15](t))*((20.0α₁[15](t) - 20.0α₁[14](t))^2)) / (((20.0α₁[15](t) - 20.0α₁[14](t))^2 + (20.0α₂[15](t) - 20.0α₂[14](t))^2)*α₂[15](t)) + Differential(t)((20.0α₁[15](t) - 20.0α₁[14](t))^2 + (20.0α₂[15](t) - 20.0α₂[14](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.725)(α₂[16](t))*Differential(0.725)(Differential(0.725)(α₁[16](t)))) > 0, 2(20.0α₁[16](t) - 20.0α₁[15](t))*Differential(0.725)(α₂[16](t))*Differential(0.725)(Differential(0.725)(α₁[16](t))), 2(20.0α₁[17](t) - 20.0α₁[16](t))*Differential(0.725)(α₂[16](t))*Differential(0.725)(Differential(0.725)(α₁[16](t)))) - 2.0(399.99999999999994α₂[15](t) + 399.99999999999994α₂[17](t) - 799.9999999999999α₂[16](t))*((20.0α₁[16](t) - 20.0α₁[15](t))^2)) / (((20.0α₁[16](t) - 20.0α₁[15](t))^2 + (20.0α₂[16](t) - 20.0α₂[15](t))^2)*α₂[16](t)) + Differential(t)((20.0α₁[16](t) - 20.0α₁[15](t))^2 + (20.0α₂[16](t) - 20.0α₂[15](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.775)(α₂[17](t))*Differential(0.775)(Differential(0.775)(α₁[17](t)))) > 0, 2(20.0α₁[17](t) - 20.0α₁[16](t))*Differential(0.775)(α₂[17](t))*Differential(0.775)(Differential(0.775)(α₁[17](t))), 2(20.0α₁[18](t) - 20.0α₁[17](t))*Differential(0.775)(α₂[17](t))*Differential(0.775)(Differential(0.775)(α₁[17](t)))) - 2.0(399.99999999999994α₂[16](t) + 399.99999999999994α₂[18](t) - 799.9999999999999α₂[17](t))*((20.0α₁[17](t) - 20.0α₁[16](t))^2)) / (((20.0α₁[17](t) - 20.0α₁[16](t))^2 + (20.0α₂[17](t) - 20.0α₂[16](t))^2)*α₂[17](t)) + Differential(t)((20.0α₁[17](t) - 20.0α₁[16](t))^2 + (20.0α₂[17](t) - 20.0α₂[16](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.825)(α₂[18](t))*Differential(0.825)(Differential(0.825)(α₁[18](t)))) > 0, 2(20.0α₁[18](t) - 20.0α₁[17](t))*Differential(0.825)(α₂[18](t))*Differential(0.825)(Differential(0.825)(α₁[18](t))), 2(20.0α₁[19](t) - 20.0α₁[18](t))*Differential(0.825)(α₂[18](t))*Differential(0.825)(Differential(0.825)(α₁[18](t)))) - 2.0(399.99999999999994α₂[17](t) + 399.99999999999994α₂[19](t) - 799.9999999999999α₂[18](t))*((20.0α₁[18](t) - 20.0α₁[17](t))^2)) / (((20.0α₁[18](t) - 20.0α₁[17](t))^2 + (20.0α₂[18](t) - 20.0α₂[17](t))^2)*α₂[18](t)) + Differential(t)((20.0α₁[18](t) - 20.0α₁[17](t))^2 + (20.0α₂[18](t) - 20.0α₂[17](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.875)(α₂[19](t))*Differential(0.875)(Differential(0.875)(α₁[19](t)))) > 0, 2(20.0α₁[19](t) - 20.0α₁[18](t))*Differential(0.875)(α₂[19](t))*Differential(0.875)(Differential(0.875)(α₁[19](t))), 2(20.0α₁[20](t) - 20.0α₁[19](t))*Differential(0.875)(α₂[19](t))*Differential(0.875)(Differential(0.875)(α₁[19](t)))) - 2.0(399.99999999999994α₂[18](t) + 399.99999999999994α₂[20](t) - 799.9999999999999α₂[19](t))*((20.0α₁[19](t) - 20.0α₁[18](t))^2)) / (((20.0α₁[19](t) - 20.0α₁[18](t))^2 + (20.0α₂[19](t) - 20.0α₂[18](t))^2)*α₂[19](t)) + Differential(t)((20.0α₁[19](t) - 20.0α₁[18](t))^2 + (20.0α₂[19](t) - 20.0α₂[18](t))^2) ~ 0, (IfElse.ifelse((2Differential(0.925)(α₂[20](t))*Differential(0.925)(Differential(0.925)(α₁[20](t)))) > 0, 2(20.0α₁[20](t) - 20.0α₁[19](t))*Differential(0.925)(α₂[20](t))*Differential(0.925)(Differential(0.925)(α₁[20](t))), 2(20.0α₁[21](t) - 20.0α₁[20](t))*Differential(0.925)(α₂[20](t))*Differential(0.925)(Differential(0.925)(α₁[20](t)))) - 2.0(399.99999999999994α₂[19](t) + 399.99999999999994α₂[21](t) - 799.9999999999999α₂[20](t))*((20.0α₁[20](t) - 20.0α₁[19](t))^2)) / (((20.0α₁[20](t) - 20.0α₁[19](t))^2 + (20.0α₂[20](t) - 20.0α₂[19](t))^2)*α₂[20](t)) + Differential(t)((20.0α₁[20](t) - 20.0α₁[19](t))^2 + (20.0α₂[20](t) - 20.0α₂[19](t))^2) ~ 0, (IfElse.ifelse((2α₂[2](t)*Differential(0.025)(α₂[2](t))*Differential(0.025)(Differential(0.025)(α₁[2](t)))) > 0, 2(20.0α₁[2](t) - 20.0α₁[1](t))*α₂[2](t)*Differential(0.025)(α₂[2](t))*Differential(0.025)(Differential(0.025)(α₁[2](t))), 2(20.0α₁[3](t) - 20.0α₁[2](t))*α₂[2](t)*Differential(0.025)(α₂[2](t))*Differential(0.025)(Differential(0.025)(α₁[2](t)))) - (2//1)*(399.99999999999994α₂[1](t) + 399.99999999999994α₂[3](t) - 799.9999999999999α₂[2](t))*((20.0α₁[2](t) - 20.0α₁[1](t))^2)*α₂[2](t)) / (((20.0α₁[2](t) - 20.0α₁[1](t))^2 + (20.0α₂[2](t) - 20.0α₂[1](t))^2)^2) + Differential(t)(α₂[2](t)^2) ~ 0, (IfElse.ifelse((2α₂[3](t)*Differential(0.075)(α₂[3](t))*Differential(0.075)(Differential(0.075)(α₁[3](t)))) > 0, 2(20.0α₁[3](t) - 20.0α₁[2](t))*α₂[3](t)*Differential(0.075)(α₂[3](t))*Differential(0.075)(Differential(0.075)(α₁[3](t))), 2(20.0α₁[4](t) - 20.0α₁[3](t))*α₂[3](t)*Differential(0.075)(α₂[3](t))*Differential(0.075)(Differential(0.075)(α₁[3](t)))) - (2//1)*(399.99999999999994α₂[2](t) + 399.99999999999994α₂[4](t) - 799.9999999999999α₂[3](t))*((20.0α₁[3](t) - 20.0α₁[2](t))^2)*α₂[3](t)) / (((20.0α₁[3](t) - 20.0α₁[2](t))^2 + (20.0α₂[3](t) - 20.0α₂[2](t))^2)^2) + Differential(t)(α₂[3](t)^2) ~ 0, (IfElse.ifelse((2α₂[4](t)*Differential(0.125)(α₂[4](t))*Differential(0.125)(Differential(0.125)(α₁[4](t)))) > 0, 2(20.0α₁[4](t) - 20.0α₁[3](t))*α₂[4](t)*Differential(0.125)(α₂[4](t))*Differential(0.125)(Differential(0.125)(α₁[4](t))), 2(20.0α₁[5](t) - 20.0α₁[4](t))*α₂[4](t)*Differential(0.125)(α₂[4](t))*Differential(0.125)(Differential(0.125)(α₁[4](t)))) - (2//1)*(399.99999999999994α₂[3](t) + 399.99999999999994α₂[5](t) - 799.9999999999999α₂[4](t))*((20.0α₁[4](t) - 20.0α₁[3](t))^2)*α₂[4](t)) / (((20.0α₁[4](t) - 20.0α₁[3](t))^2 + (20.0α₂[4](t) - 20.0α₂[3](t))^2)^2) + Differential(t)(α₂[4](t)^2) ~ 0, (IfElse.ifelse((2α₂[5](t)*Differential(0.175)(α₂[5](t))*Differential(0.175)(Differential(0.175)(α₁[5](t)))) > 0, 2(20.0α₁[5](t) - 20.0α₁[4](t))*α₂[5](t)*Differential(0.175)(α₂[5](t))*Differential(0.175)(Differential(0.175)(α₁[5](t))), 2(20.0α₁[6](t) - 20.0α₁[5](t))*α₂[5](t)*Differential(0.175)(α₂[5](t))*Differential(0.175)(Differential(0.175)(α₁[5](t)))) - (2//1)*(399.99999999999994α₂[4](t) + 399.99999999999994α₂[6](t) - 799.9999999999999α₂[5](t))*((20.0α₁[5](t) - 20.0α₁[4](t))^2)*α₂[5](t)) / (((20.0α₁[5](t) - 20.0α₁[4](t))^2 + (20.0α₂[5](t) - 20.0α₂[4](t))^2)^2) + Differential(t)(α₂[5](t)^2) ~ 0, (IfElse.ifelse((2α₂[6](t)*Differential(0.225)(α₂[6](t))*Differential(0.225)(Differential(0.225)(α₁[6](t)))) > 0, 2(20.0α₁[6](t) - 20.0α₁[5](t))*α₂[6](t)*Differential(0.225)(α₂[6](t))*Differential(0.225)(Differential(0.225)(α₁[6](t))), 2(20.0α₁[7](t) - 20.0α₁[6](t))*α₂[6](t)*Differential(0.225)(α₂[6](t))*Differential(0.225)(Differential(0.225)(α₁[6](t)))) - (2//1)*(399.99999999999994α₂[5](t) + 399.99999999999994α₂[7](t) - 799.9999999999999α₂[6](t))*((20.0α₁[6](t) - 20.0α₁[5](t))^2)*α₂[6](t)) / (((20.0α₁[6](t) - 20.0α₁[5](t))^2 + (20.0α₂[6](t) - 20.0α₂[5](t))^2)^2) + Differential(t)(α₂[6](t)^2) ~ 0, (IfElse.ifelse((2α₂[7](t)*Differential(0.275)(α₂[7](t))*Differential(0.275)(Differential(0.275)(α₁[7](t)))) > 0, 2(20.0α₁[7](t) - 20.0α₁[6](t))*α₂[7](t)*Differential(0.275)(α₂[7](t))*Differential(0.275)(Differential(0.275)(α₁[7](t))), 2(20.0α₁[8](t) - 20.0α₁[7](t))*α₂[7](t)*Differential(0.275)(α₂[7](t))*Differential(0.275)(Differential(0.275)(α₁[7](t)))) - (2//1)*(399.99999999999994α₂[6](t) + 399.99999999999994α₂[8](t) - 799.9999999999999α₂[7](t))*((20.0α₁[7](t) - 20.0α₁[6](t))^2)*α₂[7](t)) / (((20.0α₁[7](t) - 20.0α₁[6](t))^2 + (20.0α₂[7](t) - 20.0α₂[6](t))^2)^2) + Differential(t)(α₂[7](t)^2) ~ 0, (IfElse.ifelse((2α₂[8](t)*Differential(0.325)(α₂[8](t))*Differential(0.325)(Differential(0.325)(α₁[8](t)))) > 0, 2(20.0α₁[8](t) - 20.0α₁[7](t))*α₂[8](t)*Differential(0.325)(α₂[8](t))*Differential(0.325)(Differential(0.325)(α₁[8](t))), 2(20.0α₁[9](t) - 20.0α₁[8](t))*α₂[8](t)*Differential(0.325)(α₂[8](t))*Differential(0.325)(Differential(0.325)(α₁[8](t)))) - (2//1)*(399.99999999999994α₂[7](t) + 399.99999999999994α₂[9](t) - 799.9999999999999α₂[8](t))*((20.0α₁[8](t) - 20.0α₁[7](t))^2)*α₂[8](t)) / (((20.0α₁[8](t) - 20.0α₁[7](t))^2 + (20.0α₂[8](t) - 20.0α₂[7](t))^2)^2) + Differential(t)(α₂[8](t)^2) ~ 0, (IfElse.ifelse((2α₂[9](t)*Differential(0.375)(α₂[9](t))*Differential(0.375)(Differential(0.375)(α₁[9](t)))) > 0, 2(20.0α₁[9](t) - 20.0α₁[8](t))*α₂[9](t)*Differential(0.375)(α₂[9](t))*Differential(0.375)(Differential(0.375)(α₁[9](t))), 2(20.0α₁[10](t) - 20.0α₁[9](t))*α₂[9](t)*Differential(0.375)(α₂[9](t))*Differential(0.375)(Differential(0.375)(α₁[9](t)))) - (2//1)*(399.99999999999994α₂[8](t) + 399.99999999999994α₂[10](t) - 799.9999999999999α₂[9](t))*((20.0α₁[9](t) - 20.0α₁[8](t))^2)*α₂[9](t)) / (((20.0α₁[9](t) - 20.0α₁[8](t))^2 + (20.0α₂[9](t) - 20.0α₂[8](t))^2)^2) + Differential(t)(α₂[9](t)^2) ~ 0, (IfElse.ifelse((2α₂[10](t)*Differential(0.425)(α₂[10](t))*Differential(0.425)(Differential(0.425)(α₁[10](t)))) > 0, 2(20.0α₁[10](t) - 20.0α₁[9](t))*α₂[10](t)*Differential(0.425)(α₂[10](t))*Differential(0.425)(Differential(0.425)(α₁[10](t))), 2(20.0α₁[11](t) - 20.0α₁[10](t))*α₂[10](t)*Differential(0.425)(α₂[10](t))*Differential(0.425)(Differential(0.425)(α₁[10](t)))) - (2//1)*(399.99999999999994α₂[9](t) + 399.99999999999994α₂[11](t) - 799.9999999999999α₂[10](t))*((20.0α₁[10](t) - 20.0α₁[9](t))^2)*α₂[10](t)) / (((20.0α₁[10](t) - 20.0α₁[9](t))^2 + (20.0α₂[10](t) - 20.0α₂[9](t))^2)^2) + Differential(t)(α₂[10](t)^2) ~ 0, (IfElse.ifelse((2α₂[11](t)*Differential(0.475)(α₂[11](t))*Differential(0.475)(Differential(0.475)(α₁[11](t)))) > 0, 2(20.0α₁[11](t) - 20.0α₁[10](t))*α₂[11](t)*Differential(0.475)(α₂[11](t))*Differential(0.475)(Differential(0.475)(α₁[11](t))), 2(20.0α₁[12](t) - 20.0α₁[11](t))*α₂[11](t)*Differential(0.475)(α₂[11](t))*Differential(0.475)(Differential(0.475)(α₁[11](t)))) - (2//1)*(399.99999999999994α₂[10](t) + 399.99999999999994α₂[12](t) - 799.9999999999999α₂[11](t))*((20.0α₁[11](t) - 20.0α₁[10](t))^2)*α₂[11](t)) / (((20.0α₁[11](t) - 20.0α₁[10](t))^2 + (20.0α₂[11](t) - 20.0α₂[10](t))^2)^2) + Differential(t)(α₂[11](t)^2) ~ 0, (IfElse.ifelse((2α₂[12](t)*Differential(0.525)(α₂[12](t))*Differential(0.525)(Differential(0.525)(α₁[12](t)))) > 0, 2(20.0α₁[12](t) - 20.0α₁[11](t))*α₂[12](t)*Differential(0.525)(α₂[12](t))*Differential(0.525)(Differential(0.525)(α₁[12](t))), 2(20.0α₁[13](t) - 20.0α₁[12](t))*α₂[12](t)*Differential(0.525)(α₂[12](t))*Differential(0.525)(Differential(0.525)(α₁[12](t)))) - (2//1)*(399.99999999999994α₂[11](t) + 399.99999999999994α₂[13](t) - 799.9999999999999α₂[12](t))*((20.0α₁[12](t) - 20.0α₁[11](t))^2)*α₂[12](t)) / (((20.0α₁[12](t) - 20.0α₁[11](t))^2 + (20.0α₂[12](t) - 20.0α₂[11](t))^2)^2) + Differential(t)(α₂[12](t)^2) ~ 0, (IfElse.ifelse((2α₂[13](t)*Differential(0.575)(α₂[13](t))*Differential(0.575)(Differential(0.575)(α₁[13](t)))) > 0, 2(20.0α₁[13](t) - 20.0α₁[12](t))*α₂[13](t)*Differential(0.575)(α₂[13](t))*Differential(0.575)(Differential(0.575)(α₁[13](t))), 2(20.0α₁[14](t) - 20.0α₁[13](t))*α₂[13](t)*Differential(0.575)(α₂[13](t))*Differential(0.575)(Differential(0.575)(α₁[13](t)))) - (2//1)*(399.99999999999994α₂[12](t) + 399.99999999999994α₂[14](t) - 799.9999999999999α₂[13](t))*((20.0α₁[13](t) - 20.0α₁[12](t))^2)*α₂[13](t)) / (((20.0α₁[13](t) - 20.0α₁[12](t))^2 + (20.0α₂[13](t) - 20.0α₂[12](t))^2)^2) + Differential(t)(α₂[13](t)^2) ~ 0, (IfElse.ifelse((2α₂[14](t)*Differential(0.625)(α₂[14](t))*Differential(0.625)(Differential(0.625)(α₁[14](t)))) > 0, 2(20.0α₁[14](t) - 20.0α₁[13](t))*α₂[14](t)*Differential(0.625)(α₂[14](t))*Differential(0.625)(Differential(0.625)(α₁[14](t))), 2(20.0α₁[15](t) - 20.0α₁[14](t))*α₂[14](t)*Differential(0.625)(α₂[14](t))*Differential(0.625)(Differential(0.625)(α₁[14](t)))) - (2//1)*(399.99999999999994α₂[13](t) + 399.99999999999994α₂[15](t) - 799.9999999999999α₂[14](t))*((20.0α₁[14](t) - 20.0α₁[13](t))^2)*α₂[14](t)) / (((20.0α₁[14](t) - 20.0α₁[13](t))^2 + (20.0α₂[14](t) - 20.0α₂[13](t))^2)^2) + Differential(t)(α₂[14](t)^2) ~ 0, (IfElse.ifelse((2α₂[15](t)*Differential(0.675)(α₂[15](t))*Differential(0.675)(Differential(0.675)(α₁[15](t)))) > 0, 2(20.0α₁[15](t) - 20.0α₁[14](t))*α₂[15](t)*Differential(0.675)(α₂[15](t))*Differential(0.675)(Differential(0.675)(α₁[15](t))), 2(20.0α₁[16](t) - 20.0α₁[15](t))*α₂[15](t)*Differential(0.675)(α₂[15](t))*Differential(0.675)(Differential(0.675)(α₁[15](t)))) - (2//1)*(399.99999999999994α₂[14](t) + 399.99999999999994α₂[16](t) - 799.9999999999999α₂[15](t))*((20.0α₁[15](t) - 20.0α₁[14](t))^2)*α₂[15](t)) / (((20.0α₁[15](t) - 20.0α₁[14](t))^2 + (20.0α₂[15](t) - 20.0α₂[14](t))^2)^2) + Differential(t)(α₂[15](t)^2) ~ 0, (IfElse.ifelse((2α₂[16](t)*Differential(0.725)(α₂[16](t))*Differential(0.725)(Differential(0.725)(α₁[16](t)))) > 0, 2(20.0α₁[16](t) - 20.0α₁[15](t))*α₂[16](t)*Differential(0.725)(α₂[16](t))*Differential(0.725)(Differential(0.725)(α₁[16](t))), 2(20.0α₁[17](t) - 20.0α₁[16](t))*α₂[16](t)*Differential(0.725)(α₂[16](t))*Differential(0.725)(Differential(0.725)(α₁[16](t)))) - (2//1)*(399.99999999999994α₂[15](t) + 399.99999999999994α₂[17](t) - 799.9999999999999α₂[16](t))*((20.0α₁[16](t) - 20.0α₁[15](t))^2)*α₂[16](t)) / (((20.0α₁[16](t) - 20.0α₁[15](t))^2 + (20.0α₂[16](t) - 20.0α₂[15](t))^2)^2) + Differential(t)(α₂[16](t)^2) ~ 0, (IfElse.ifelse((2α₂[17](t)*Differential(0.775)(α₂[17](t))*Differential(0.775)(Differential(0.775)(α₁[17](t)))) > 0, 2(20.0α₁[17](t) - 20.0α₁[16](t))*α₂[17](t)*Differential(0.775)(α₂[17](t))*Differential(0.775)(Differential(0.775)(α₁[17](t))), 2(20.0α₁[18](t) - 20.0α₁[17](t))*α₂[17](t)*Differential(0.775)(α₂[17](t))*Differential(0.775)(Differential(0.775)(α₁[17](t)))) - (2//1)*(399.99999999999994α₂[16](t) + 399.99999999999994α₂[18](t) - 799.9999999999999α₂[17](t))*((20.0α₁[17](t) - 20.0α₁[16](t))^2)*α₂[17](t)) / (((20.0α₁[17](t) - 20.0α₁[16](t))^2 + (20.0α₂[17](t) - 20.0α₂[16](t))^2)^2) + Differential(t)(α₂[17](t)^2) ~ 0, (IfElse.ifelse((2α₂[18](t)*Differential(0.825)(α₂[18](t))*Differential(0.825)(Differential(0.825)(α₁[18](t)))) > 0, 2(20.0α₁[18](t) - 20.0α₁[17](t))*α₂[18](t)*Differential(0.825)(α₂[18](t))*Differential(0.825)(Differential(0.825)(α₁[18](t))), 2(20.0α₁[19](t) - 20.0α₁[18](t))*α₂[18](t)*Differential(0.825)(α₂[18](t))*Differential(0.825)(Differential(0.825)(α₁[18](t)))) - (2//1)*(399.99999999999994α₂[17](t) + 399.99999999999994α₂[19](t) - 799.9999999999999α₂[18](t))*((20.0α₁[18](t) - 20.0α₁[17](t))^2)*α₂[18](t)) / (((20.0α₁[18](t) - 20.0α₁[17](t))^2 + (20.0α₂[18](t) - 20.0α₂[17](t))^2)^2) + Differential(t)(α₂[18](t)^2) ~ 0, (IfElse.ifelse((2α₂[19](t)*Differential(0.875)(α₂[19](t))*Differential(0.875)(Differential(0.875)(α₁[19](t)))) > 0, 2(20.0α₁[19](t) - 20.0α₁[18](t))*α₂[19](t)*Differential(0.875)(α₂[19](t))*Differential(0.875)(Differential(0.875)(α₁[19](t))), 2(20.0α₁[20](t) - 20.0α₁[19](t))*α₂[19](t)*Differential(0.875)(α₂[19](t))*Differential(0.875)(Differential(0.875)(α₁[19](t)))) - (2//1)*(399.99999999999994α₂[18](t) + 399.99999999999994α₂[20](t) - 799.9999999999999α₂[19](t))*((20.0α₁[19](t) - 20.0α₁[18](t))^2)*α₂[19](t)) / (((20.0α₁[19](t) - 20.0α₁[18](t))^2 + (20.0α₂[19](t) - 20.0α₂[18](t))^2)^2) + Differential(t)(α₂[19](t)^2) ~ 0, (IfElse.ifelse((2α₂[20](t)*Differential(0.925)(α₂[20](t))*Differential(0.925)(Differential(0.925)(α₁[20](t)))) > 0, 2(20.0α₁[20](t) - 20.0α₁[19](t))*α₂[20](t)*Differential(0.925)(α₂[20](t))*Differential(0.925)(Differential(0.925)(α₁[20](t))), 2(20.0α₁[21](t) - 20.0α₁[20](t))*α₂[20](t)*Differential(0.925)(α₂[20](t))*Differential(0.925)(Differential(0.925)(α₁[20](t)))) - (2//1)*(399.99999999999994α₂[19](t) + 399.99999999999994α₂[21](t) - 799.9999999999999α₂[20](t))*((20.0α₁[20](t) - 20.0α₁[19](t))^2)*α₂[20](t)) / (((20.0α₁[20](t) - 20.0α₁[19](t))^2 + (20.0α₂[20](t) - 20.0α₂[19](t))^2)^2) + Differential(t)(α₂[20](t)^2) ~ 0, (IfElse.ifelse((2α₂[21](t)*Differential(0.975)(α₂[21](t))*Differential(0.975)(Differential(0.975)(α₁[21](t)))) > 0, 2(20.0α₁[21](t) - 20.0α₁[20](t))*α₂[21](t)*Differential(0.975)(α₂[21](t))*Differential(0.975)(Differential(0.975)(α₁[21](t))), 2(20.0α₁[22](t) - 20.0α₁[21](t))*α₂[21](t)*Differential(0.975)(α₂[21](t))*Differential(0.975)(Differential(0.975)(α₁[21](t)))) - (2//1)*(399.99999999999994α₂[20](t) + 399.99999999999994α₂[22](t) - 799.9999999999999α₂[21](t))*((20.0α₁[21](t) - 20.0α₁[20](t))^2)*α₂[21](t)) / (((20.0α₁[21](t) - 20.0α₁[20](t))^2 + (20.0α₂[21](t) - 20.0α₂[20](t))^2)^2) + Differential(t)(α₂[21](t)^2) ~ 0, 0.5α₂[1](t) + 0.5α₂[2](t) ~ 0.0, 0.5α₂[21](t) + 0.5α₂[22](t) ~ 0.0, 20.0α₂[2](t) - 20.0α₂[1](t) ~ 1.0, 20.0α₂[22](t) - 20.0α₂[21](t) ~ -1.0, 20.0α₁[2](t) - 20.0α₁[1](t) ~ 0.0, 20.0α₁[22](t) - 20.0α₁[21](t) ~ 0.0]

Discretization failed, please post an issue on https://github.com/SciML/MethodOfLines.jl with the failing code and system at low point count.

ERROR: MethodError: no method matching collect_ivs_from_nested_operator!(::Set{Any}, ::SymbolicUtils.Add{Real, Int64, Dict{Any, Number}, Nothing}, ::Type{Differential})
Closest candidates are:
  collect_ivs_from_nested_operator!(::Any, ::Term, ::Any) at ~/.julia/packages/ModelingToolkit/vZUs5/src/utils.jl:188
Stacktrace:
 [1] collect_ivs_from_nested_operator!(ivs::Set{Any}, x::Term{Real, Nothing}, target_op::Type)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/vZUs5/src/utils.jl:192
 [2] collect_ivs(eqs::Vector{Equation}, op::Type)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/vZUs5/src/utils.jl:163
 [3] collect_ivs
   @ ~/.julia/packages/ModelingToolkit/vZUs5/src/utils.jl:157 [inlined]
 [4] check_equations(eqs::Vector{Equation}, iv::Sym{Real, Base.ImmutableDict{DataType, Any}})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/vZUs5/src/utils.jl:177
 [5] ODESystem(deqs::Vector{Equation}, iv::Sym{Real, Base.ImmutableDict{DataType, Any}}, dvs::Vector{Term{Real, Base.ImmutableDict{DataType, Any}}}, ps::Vector{Any}, var_to_name::Dict{Any, Any}, ctrls::Vector{Any}, observed::Vector{Equation}, tgrad::Base.RefValue{Vector{Num}}, jac::Base.RefValue{Any}, ctrl_jac::Base.RefValue{Any}, Wfact::Base.RefValue{Matrix{Num}}, Wfact_t::Base.RefValue{Matrix{Num}}, name::Symbol, systems::Vector{ODESystem}, defaults::Dict{Any, Any}, torn_matching::Nothing, connector_type::Nothing, connections::Nothing, preface::Nothing, events::Vector{ModelingToolkit.SymbolicContinuousCallback}, tearing_state::Nothing, substitutions::Nothing; checks::Bool)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/vZUs5/src/systems/diffeqs/odesystem.jl:121
 [6] ODESystem(deqs::Vector{Equation}, iv::Num, dvs::Vector{Num}, ps::Vector{Num}; controls::Vector{Num}, observed::Vector{Equation}, systems::Vector{ODESystem}, name::Symbol, default_u0::Dict{Any, Any}, default_p::Dict{Any, Any}, defaults::Dict{Num, Float64}, connector_type::Nothing, preface::Nothing, continuous_events::Nothing, checks::Bool)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/vZUs5/src/systems/diffeqs/odesystem.jl:175
 [7] symbolic_discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.EdgeAlignedGrid})
   @ MethodOfLines ~/.julia/packages/MethodOfLines/5wITU/src/MOL_discretization.jl:126
 [8] discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.EdgeAlignedGrid})
   @ MethodOfLines ~/.julia/packages/MethodOfLines/5wITU/src/MOL_discretization.jl:148
 [9] top-level scope
   @ REPL[39]:1
```

Code to reproduce:
```julia
using ModelingToolkit, DomainSets, MethodOfLines
@parameters x t
@variables α₁(..) α₂(..);
# "time" derivative
Dt = Differential(t)
	
# spacial coordinates
Dx = Differential(x)

eqs = [
    Differential(t)(Differential(x)(α₁(t, x))^2 + Differential(x)(α₂(t, x))^2) ~ (2.0(Differential(x)(α₁(t, x))^2)*Differential(x)(Differential(x)(α₂(t, x))) - 2Differential(x)(Differential(x)(α₁(t, x)))*Differential(x)(α₁(t, x))*Differential(x)(α₂(t, x))) / ((Differential(x)(α₁(t, x))^2 + Differential(x)(α₂(t, x))^2)*α₂(t, x)),
    Differential(t)(α₂(t, x)^2) ~ ((2//1)*(Differential(x)(α₁(t, x))^2)*Differential(x)(Differential(x)(α₂(t, x)))*α₂(t, x) - 2Differential(x)(Differential(x)(α₁(t, x)))*Differential(x)(α₁(t, x))*Differential(x)(α₂(t, x))*α₂(t, x)) / ((Differential(x)(α₁(t, x))^2 + Differential(x)(α₂(t, x))^2)^2),
]

domains = [
	x ∈ Interval(0.0, 1.0),
	t ∈ Interval(0.0, 0.1),
    ]

bcs = [
	# initial shape
	α₁(0, x) ~ cos(π*x),
	α₂(0, x) ~ sin(π*x),

	# the curve hits OX at the ends
	α₂(t, 0) ~ 0.0,
	α₂(t, 1) ~ 0.0,

	# with positive derivative
	Dx(α₂(t,0)) ~  1.0,
	Dx(α₂(t,1)) ~ -1.0,
	
	# on the other hand x coordinate doesn't vary close to the ends
	Dx(α₁(t, 0)) ~ 0.0,
	Dx(α₁(t, 1)) ~ 0.0,
]

@named pdesys = PDESystem(
	eqs,
	bcs,
	domains,
	[t, x],
	[α₁(t,x), α₂(t,x)]
);

dx = 0.05
order = 3
discretization = MOLFiniteDifference(
	[x => dx],
	t,
	aprox_order=order,
	grid_align = MethodOfLines.edge_align
)
prob = discretize(pdesys, discretization)
```

```julia
  [28f2ccd6] ApproxFun v0.13.3
  [5b8099bc] DomainSets v0.5.11
  [94925ecb] MethodOfLines v0.3.2
  [961ee093] ModelingToolkit v8.13.3
  [1dea7af3] OrdinaryDiffEq v6.19.0
  [90137ffa] StaticArrays v1.4.5
  [37e2e46d] LinearAlgebra
```

### PR DESCRIPTION
**Pull request by xtalax**
fixes #102 
fixes #136 
fixes #143 
fixes #141

TODO:
- [x] Implement Basic Scheme.
- [x] Handle Boundaries:
    - [x] Handle periodic
    - [x] Extrapolate with high order scheme to ensure equation balance/validity. 
- [x] Extend interface to provide WENO as an option for 1st order derivatives.
- [x] Test.
- [x] Document.

Any comments on possible Interface designs or boundary handling welcome.

Stretch:
- [ ] Generate WENO stencils with fornberg.
- [ ] Directly calculate WENO parameter Formulae (for betas).
- [ ] Extend to nonuniform case.
- [ ] Extend to arbitrary derivative order.

### CODE REVIEW

**Comment by xtalax** [comment]
@ChrisRackauckas Any remaining fails are test errors due to the `u[1:N](t) -> u(t)[1:N]` change, can you review?

File: src/MOL_discretization.jl [hunk 1]
```diff
@@ -123,6 +128,7 @@ function SciMLBase.symbolic_discretize(pdesys::PDESystem, discretization::Method
         else
             # * In the end we have reduced the problem to a system of equations in terms of Dt that can be solved by an ODE solver.
 
+           # Main.xx[] = vcat(alleqs, unique(bceqs)), t, vec(reduce(vcat, vec(alldepvarsdisc))), ps, Dict(defaults), pdesys.name
```
Comment (ChrisRackauckas) [inline src/MOL_discretization.jl:131]:
```suggestion
```

File: src/discretization/discretize_vars.jl [hunk 2]
```diff
@@ -83,6 +84,7 @@ struct DiscreteSpace{N,M,G}
     Iaxies
     Igrid
     x2i
+    errvar # The error variable for the discrete space
```
Comment (ChrisRackauckas) [inline src/discretization/discretize_vars.jl:87]: What is this?

File: src/discretization/generate_bc_eqs.jl [hunk 3]
```diff
@@ -105,6 +105,55 @@ function generate_bc_eqs(s::DiscreteSpace{N,M,G}, boundaryvalfuncs, boundary::Ab
     end)
 end
 
+"""
+`generate_extrap_eqs`
+
+Pads the boundaries with extrapolation equations, extrapolated with 6th order lagrangian polynomials.
```
Comment (ChrisRackauckas) [inline src/discretization/generate_bc_eqs.jl:111]: Why 6th?

File: src/discretization/discretize_vars.jl [hunk 4]
```diff
@@ -142,15 +144,17 @@ function DiscreteSpace(domain, depvars, x̄, discretization::MOLFiniteDifference
             u => fill(first(@variables($sym(t))), ()) #Create a 0-dimensional array
         else
             uaxes = collect(axes(grid[x])[1] for x in remove(arguments(u), t))
-            u => collect(first(@variables $sym[uaxes...](t)))
+            u => collect(first(@variables $sym(t)[uaxes...]))
         end
     end
 
+    @parameters errvar
```
Comment (ChrisRackauckas) [inline src/discretization/discretize_vars.jl:151]: Is this used anywhere?

File: src/discretization/schemes/WENO/WENO.jl [hunk 5]
```diff
@@ -0,0 +1,89 @@
+
+"""
+Implements the WENO scheme of Jiang and Shu.
+
+Specified in https://repository.library.brown.edu/studio/item/bdr:297524/PDF/ (Page 8-9)
+
+Implementation *heavily* inspired by https://github.com/ranocha/HyperbolicDiffEq.jl/blob/84c2d882e0c8956457c7d662bf7f18e3c27cfa3d/src/finite_volumes/weno_jiang_shu.jl by H. Ranocha.
+"""
+@inline function weno(II::CartesianIndex, s::DiscreteSpace, wenoscheme::WENOScheme, b, jx, u, dx::Number)
```
Comment (ChrisRackauckas) [inline src/discretization/schemes/WENO/WENO.jl:9]: why inline?

File: test/pde_systems/burgers_eq.jl [hunk 6]
```diff
@@ -91,93 +144,92 @@ end
...
 # Exact solutions from: https://www.sciencedirect.com/science/article/pii/S0898122110003883
-@testset "Test 01: Burger's Equation 2D" begin
-    @parameters x y t
-    @variables u(..) v(..)
-    Dt = Differential(t)
-    Dx = Differential(x)
-    Dy = Differential(y)
-    Dxx = Differential(x)^2
-    Dyy = Differential(y)^2
+# @testset "Test 01: Burger's Equation 2D" begin
```
Comment (ChrisRackauckas) [inline test/pde_systems/burgers_eq.jl:147]: ?

File: src/discretization/discretize_vars.jl (hunk 2 above)
Comment (xtalax) [reply src/discretization/discretize_vars.jl:87]: I added this to track when schemes were applied outside of their range of validity. It has served its purpose, I will remove.

File: src/discretization/generate_bc_eqs.jl (hunk 3 above)
Comment (xtalax) [reply src/discretization/generate_bc_eqs.jl:111]: To maintain 5th order accuracy for weno, it is used in the spec.

File: src/discretization/schemes/WENO/WENO.jl (hunk 5 above)
Comment (xtalax) [reply src/discretization/schemes/WENO/WENO.jl:9]: Just a habit I established from earlier schemes, should it not?

File: test/pde_systems/burgers_eq.jl (hunk 6 above)
Comment (xtalax) [reply test/pde_systems/burgers_eq.jl:147]: This has never passed, I'm not sure its even correct.

**Review by ChrisRackauckas — APPROVED** [review]
